### ISSUE TITLE
Decide on whether to use Shiny modules

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/snackman#24]
We decided to seperate logic from visualization (issue #13). Shiny modules are one way of implementing this architecture principle.  Hadley Wickham's [chapter on modules](https://mastering-shiny.org/scaling-modules.html) in _Mastering Shiny_ may be of interest for this issue.

**Comment by richelbilderbeek** [comment]
Sounds like #28 it is :+1:

**Comment by FrieseWoudloper** [comment]
A simple example of the usage of modules.

```
library(shiny)

histogramUI <- function(id) {
  tagList(
    selectInput(NS(id, "var"), "Variable", names(mtcars)),
    numericInput(NS(id, "bins"), "bins", 10, min = 1),
    plotOutput(NS(id, "hist"))
  )
}

histogramServer <- function(id) {
  moduleServer(id, function(input, output, session) {
    data <- reactive(mtcars[[input$var]])
    output$hist <- renderPlot({
      hist(data(), breaks = input$bins, main = input$var)
    }, res = 96)
  })
}

histogramApp <- function() {
  ui <- fluidPage(
    histogramUI("hist1"),
    histogramUI("hist2"),
    histogramUI("hist3")
  )
  server <- function(input, output, session) {
    histogramServer("hist1")
    histogramServer("hist2")
    histogramServer("hist3")    
  }
  shinyApp(ui, server)  
}

histogramApp()
```

**Comment by FrieseWoudloper** [comment]
I think we should definitely use Shiny modules for our project. It will make it easier to reuse, debug and test code. Also, if we put modules in separate files, our project will be better structured.

**Comment by FrieseWoudloper** [comment]
We can use `shiny::testServer()` to test reactive functionality. Example:
```
cyl <- c(6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 
         8, 4, 4, 4, 4, 8, 8, 8, 8, 4, 4, 4, 8, 6, 8, 4)

testServer(histogramServer, {
  session$setInputs(var = "cyl")
  testthat::expect_equal(data(), cyl)
})
```

**Comment by richelbilderbeek** [comment]
This Issue is related to #37 , where the case for `golum` is make. Let's chat tonight about this :+1:

**Comment by richelbilderbeek** [comment]
Yep, we will use Shiny modules :+1:
