### ISSUE TITLE
Add 'are_game_states_identical'

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/snackman#51]
Currently, we have no means to check if two `game_state`s are identical.

Allow the first step to do so:

```r
test_that("use", {
  skip("Issue 51. Issue #51")
  a <- create_test_game_state()
  b <- create_test_game_state()
  expect_true(are_game_states_identical(a, b))
})
```

**Comment by FrieseWoudloper** [comment]
What do we exactly mean by 'identical'?
```
game_state1 <- create_test_game_state()
game_state2 <- create_test_game_state()
game_state3 <- game_state1

identical(game_state1, game_state2)
[1] FALSE
identical(game_state1, game_state3)
[1] TRUE
```
Do we want `are_game_states_identical(game_state1, game_state2)` to return `TRUE`?

**Comment by richelbilderbeek** [comment]
> Do we want are_game_states_identical(game_state1, game_state2) to return TRUE?

Yes indeed, as shown in the test. Maybe the word `identical` is a bit of a misnomer, but I lack a better word for having the same content. If you have one, please let me know :-)
